### ISSUE TITLE
Get An Error When Adding Events To mp.events.add In JSON Format

### ISSUE THREAD

**Issue by Voxelity** [CocaColaBear/types-ragemp#1]
I'm getting an error when I try to add events in a JSON format to the mp.events.add, I understand that you recently added an overload just for this specific reason but it seems to be giving me errors. I believe this is the line of code in question, 
`
add(events: ({ [name: string]: (...args: any[]) => void; }[])): void;
`
(Line 248, index.d.ts)

I would try to fix it for you cause I understand that you are probably super business, but I don't understand that much about ts definition files so I will try to read up on some of it and maybe come up with a solution, anyways thanks for all the hard work, happy coding!

![image](https://user-images.githubusercontent.com/20241920/31888261-2c2f34ec-b7b0-11e7-858a-e9a0bc07e9a0.png)
![image](https://user-images.githubusercontent.com/20241920/31888322-6ab54b66-b7b0-11e7-8948-648d77db5f36.png)

**Comment by Voxelity** [comment]
Well, I seem to have fixed it, I don't know if this is the correct fix but it removed the error. What I did was this:


**Orginal Line 248:** `add(events: ({ [name: string]: (...args: any[]) => void; }[])): void;`
**Possible Fix Line 248:** `add(events: { [name: string]: (...args: any[]) => void; }): void;`

**Comment by CocaColaBear** [comment]
@Voxelity, thank you. I try to fix the issue in a few hours

**Comment by CocaColaBear** [comment]
Fixed
