### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by blackflex777** [CocaColaBear/types-ragemp#17]
v

**Comment by pixlcrashr** [comment]
Что ты имеешь в виду?

[Translated using DeepL](https://www.deepl.com/translator#en/ru/What%20do%20you%20mean%20by%20that%3F)

**Comment by blackflex777** [comment]
В поисках разработчика на проект на платформе ragemp.
Соответственно с оплатой.

**Comment by pixlcrashr** [comment]
Я думаю, что это неправильный адрес для твоего вопроса. Это проект с открытым исходным кодом, а не платформа для привлечения других разработчиков. Мы предлагаем вам написать сообщение на форуме в форумах RageMP.

[Translated using DeepL](https://www.deepl.com/translator#en/ru/I%20think%20this%20is%20the%20wrong%20address%20for%20your%20issue.%20This%20is%20an%20Open%20Source%20project%20-%20not%20a%20platform%20to%20recruit%20other%20developers.%20We%20suggest%20that%20you%20should%20write%20a%20forum%20post%20in%20the%20RageMP%20forums.)

Closed.
